name: Nightly builds
on:
  schedule:
    - cron: '0 21 * * *' # Run at 9 PM UTC.
  workflow_dispatch:

permissions: {}

jobs:
  build:
    if: github.repository_owner == 'co-cart'
    name: Nightly builds
    strategy:
      fail-fast: false
      matrix:
        build: [dev]
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ matrix.build }}

      - name: Build zip
        working-directory: 
        run: bash bin/nightly-build.sh

      - name: Deploy nightly build
        uses: WebFreak001/deploy-nightly@v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/${{ github.repository }}/releases/49034208/assets{?name,label}
          release_id: 49034208
          asset_path: plugins/cocart.zip
          asset_name: cocart-${{ matrix.build }}-nightly.zip
          asset_content_type: application/zip
          max_releases: 1
  update:
    name: Update nightly tag commit ref
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - name: Update nightly tag
        uses: richardsimko/github-tag-action@v1.0.5
        with:
          tag_name: nightly
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}